# Each step is the build/test process
# the name of each step is the build context, and will get its own status updates
steps:
  - name: Link docroot to codebase
    command: 'ln -s $SRC_DIR/htdocs /var/www/html'